import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'core/router/app_router.dart';
import 'injection/service_locator.dart';
import 'services/seeding_service.dart';

// Generated by FlutterFire CLI: flutterfire configure
// import 'firebase_options.dart';

/// Flip to true ONCE to seed demo data, then back to false.
const bool kSeedOnStart = false;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform,
  );

  // Register ALL dependencies before runApp — nothing calls sl() before this.
  await setupServiceLocator();

  if (kSeedOnStart) {
    await sl<SeedingService>().seed();
  }

  runApp(const RideLeafApp());
}

/// Root widget — NO BlocProvider here.
/// Each route in AppRouter provides its own BLoCs via BlocProvider.
class RideLeafApp extends StatelessWidget {
  const RideLeafApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'RideLeaf',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF1E4D35),
          brightness: Brightness.light,
        ),
      ),
      routerConfig: AppRouter.router,
    );
  }
}
